### ISSUE TITLE
How to send commands to the ADB server?

### ISSUE THREAD

**Issue by yschimke** [mobile-dev-inc/dadb#7]
The DADB implementation seems specific to the `LOCAL SERVICES`

https://cs.android.com/android/platform/superproject/+/master:packages/modules/adb/SERVICES.TXT
https://cs.android.com/android/platform/superproject/+/master:packages/modules/adb/OVERVIEW.TXT

Is there planned support for `HOST SERVICES` like devices to list the available devices?

**Comment by Leland-Takamine** [comment]
One of the core benefits of dadb is that it does not rely on the ADB server at all. This allows tools built on top of dadb to work without the prerequisite of an ADB binary. For this reason, there are no plans to support host services since they are implemented by the ADB server. We can however replicate some of the core functionality of the ADB server like listing available devices. I'll follow up with more thoughts on #8
